# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VerdaCli < Formula
  desc "Verda CLI"
  homepage "https://github.com/verda-cloud/verda-cli"
  version "1.4.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.4.1/verda_1.4.1_darwin_amd64.tar.gz"
      sha256 "b160f0baf7a5477202df05e68c18e0542d7347f2f334d64e669ec866c48ff3e3"

      define_method(:install) do
        bin.install "verda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.4.1/verda_1.4.1_darwin_arm64.tar.gz"
      sha256 "b81c4ad074e40223ad1ee1065f87c6d95105541da3c76ea6a1c6171ca579b564"

      define_method(:install) do
        bin.install "verda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.4.1/verda_1.4.1_linux_amd64.tar.gz"
      sha256 "765ce25ba822d20f6090fadd13d5b07ddbe49aa28b0890d326d5e8d098fd6cec"
      define_method(:install) do
        bin.install "verda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.4.1/verda_1.4.1_linux_arm64.tar.gz"
      sha256 "cec02f2feea819263fa2fd041440fdab8cb817c92dabf7459cbd29770b07458a"
      define_method(:install) do
        bin.install "verda"
      end
    end
  end
end
