# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class VerdaCli < Formula
  desc "Verda CLI"
  homepage "https://github.com/verda-cloud/verda-cli"
  version "1.8.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.8.0/verda_1.8.0_darwin_amd64.tar.gz"
      sha256 "ab0c1f687e77cf73899496150bb5c1c7aea41a46bf451eb5387289df7552082f"

      define_method(:install) do
        bin.install "verda"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.8.0/verda_1.8.0_darwin_arm64.tar.gz"
      sha256 "95b8c27927309e040a8669864d532eefb9404ebe834d41f5cb938d0a7d19a8b7"

      define_method(:install) do
        bin.install "verda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.8.0/verda_1.8.0_linux_amd64.tar.gz"
      sha256 "0c5710452fb58a7a6b116876b236c88a45ad7002d1651fe866ba3845a0273a41"
      define_method(:install) do
        bin.install "verda"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/verda-cloud/verda-cli/releases/download/v1.8.0/verda_1.8.0_linux_arm64.tar.gz"
      sha256 "6591f03393414dc7da6367996b0a5454f01e00a375dbb0a9dcb29128de8a15b5"
      define_method(:install) do
        bin.install "verda"
      end
    end
  end
end
